services:
  - type: web
    name: baccarat-ai-backend
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
